server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://dpg-d5fe1vchg0os73f8l8vg-a.oregon-postgres.render.com:5432/ladrillera_transversal_12
    username: root
    password: PLEYaDtlUHvnB2bG5IuKRlOmx6DD84OV
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      test-on-borrow: true
      validation-query: SELECT 1
      validation-timeout: 2000
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 20
      keepalive-time: 20000
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  version: @project.version@
  name: @project.name@
  request:
    prefix: api
    version: v1
    mappings: /back-app-catalog-core-service

springdoc:
  swagger-ui:
    path: /api/v1/back-app-catalog-core-service/swagger-ui-custom.html
  api-docs:
    path: /api/v1/back-app-catalog-core-service/api-docs

cloudinary:
  api:
    key: 458314325632755
    secret: xt1RKy_u_fgDvLuyERlqMMfyNZQ
  cloud:
    name: dgtdyrtss
  upload:
    preset: landing-page